# Generated by Django 5.2.7 on 2025-10-15 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all_students', 'All Students')], default='all_students', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('withdrawn', 'withdrawn')], default='published', max_length=16)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'queued'), ('delivered', 'delivered'), ('acknowledged', 'acknowledged')], default='queued', max_length=16)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('ack_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notices.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'state'], name='notices_del_user_id_ae4263_idx'), models.Index(fields=['announcement'], name='notices_del_announc_7c53bc_idx')],
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
